### ISSUE TITLE
Proposta para landing page

### ISSUE THREAD

**Issue by EsioFreitas** [Escola-em-Casa/landing-page-escola-em-casa#2]
Olá, me chamo Ésio Freita e cuto muito desenvolvimento frontend. Percebi que a landing page do projeto é simples e eu queria propor a criação de uma nova. A minha ideia seria seguir esse fluxo:

1. Criação do protótipo
2. Validação do protótipo 
3. Dockerização
4. Desenvolvimento
5. Ajustes 
6. Publicação

Não tenho conhecimentos em Vue. Esse projeto seria desenvolvido em ReactJs. 
Segue um exemplo de landing page que criei recentemente:  https://miaajuda.netlify.app/

**Comment by guilacerda** [comment]
Fala @EsioFreitas. Muito obrigado pela disponibilidade e visão sobre este produto.

Cara, acho super importante uma reestruturação na página, com maiores detalhes, avisos (principalmente os mais urgentes, como por exemplo: não estamos fornecendo ainda os dados patrocinados). Acho que pode começar com a issue.

Se puder fragmentar esse épico em issues menores, agradeço.

Em relação à tecnologia, vamos conversar um pouco mais. Vou marcar aqui o @joaaogui que foi quem começou com a ideia da page e criou em Vue pra ver sua opinião.

**Comment by EsioFreitas** [comment]
Obrigado @guilacerda! Como pedido, vou estruturar melhor o épico e entrego essa estruturação nessa issue. 

Além disso, penso também em um repositório para as documentações. Poderíamos conversar quais documentações são prioritárias e colocá-las em um [docsify](https://docsify.js.org/#/) para melhor visualização. Podemos conversar sobre isso depois dessa issue da landing page. No entanto, se vcs quiserem criar um repositório para eu poder criar umas issue lá e conversar na issue, seria bem legal.

Por fim, @joaaogui , queria ressaltar que para melhor entrega e agilidade, a tecnologia seja ReactJs, pois não sei nada de Vue haha

**Comment by EsioFreitas** [comment]
@guilacerda , segue como planejo o fluxo de desenvolvimento e features:

1. Prototipo
2. Config do projeto
3. Dokerizar
4. Desenvolvimento
    * Home page
        * Apresentação da aplicação
        * Como funciona
        * Um sobre a aplicação breve
        * Fornecer novidades
        * Encaminhar para a playstore
        * Encaminhar para a appstore
    * Sobre
        * Explicar a ideia
        * Explicar o contexto da aplicação 
    * Contato
        * Fornecer dados de contato
        * Fornecer dados para apoio
5. Publicação

**Comment by joaaogui** [comment]
Olá @guilacerda e @EsioFreitas, me desculpem pela demora na resposta das questões 😞. Dividirei minha resposta em tópicos para melhor compreensão:

**1. Melhorias na home-page**

Acredito que melhorias são sempre bem-vindas, e nossa home-page poderia receber várias delas. Esse fluxo que você descreveu para home page, me parece bom, porém, para evitar retrabalho, recomendo que de acordo com o maior esclarecimento de como seria essa nova proposta de estrutura e design da home page, nos comunique, para uma validação do time em geral

Caso queira propor alguma melhoria eu recomendo que crie um fork do repositório, e assim que possuir algo concreto, crie o PR.

**2. Desenvolvimento**

**Comment by joaaogui** [comment]
Olá @guilacerda e @EsioFreitas, me desculpem pela demora na resposta das questões 😞. Dividirei minha resposta em tópicos para melhor compreensão:

**1. Melhorias na home-page**

Acredito que melhorias são sempre bem-vindas, e nossa home-page poderia receber várias delas. Esse fluxo que você descreveu para home page, me parece bom, porém, para evitar retrabalho, recomendo que de acordo com o maior esclarecimento de como seria essa nova proposta de estrutura e design da home page, nos comunique, para uma validação do time em geral

Caso queira propor alguma melhoria eu recomendo que crie um fork do repositório, e assim que possuir algo concreto, crie o PR.

**2. Mudança de tecnologia**

@EsioFreitas, como disse no comentário anterior, quaisquer mudanças propostas por PR serão analisadas pelo time com bastante carinho.
Porém, mudar a linguagem do projeto é uma mudança que tem efeitos em variados fatores que podem afetar o desenvolvimento, e com isso, uma mudança que deveria ser feita somente com uma justificativa plausível. Até por que, os envolvidos na home page atualmente, não tem conhecimento em ReactJS.
Contudo, como disse, caso queira criar o PR, iremos analisar, e se for uma melhoria que julguemos válida para o projeto, ela será incrementada ao código. 

Quaisquer dúvidas estou a disposição

Valeu !

**Comment by EsioFreitas** [comment]
Ola @joaaogui! Sem problemas! Ta complicado esses dias hehe.

Mas sobre a ideia: eu quero fazer tudo do 0, visto que atualmente somente tem uma pagina com um texto e imagem. Como mostrei na mensagem acima, quero preparar todo o ambiente, fazer o prototipo, validá-lo, fazer o desenvolvimento e entregá-lo para vcs. No entanto, como é em Vue, não consigo fazer o que estou propondo, pois não sei o frame. 

Acredito que isso terá mais ganho do que perca para o projeto. :smiley:

**Comment by joaaogui** [comment]
@EsioFreitas em relação aos entregáveis(docker, protótipo) acho que seriam realmente uma boa adição ao projeto. 

Porém, o fato de voce não saber Vue.JS não é uma justificativa plausível para a mudança de linguagem. 

Caso queria desenvolver algo mais alinhado com o projeto já existente, recomendo os cursos do vue mastery: https://www.vuemastery.com/

Caso queira desenvolver algo a parte, por desejo pessoal, sinta-se a vontade! Faça um fork, desenvolva e se quiser abra um PR para nós que avaliaremos. Nosso projeto tem licença GNU GPL v3 https://github.com/Escola-em-Casa/landing-page-escola-em-casa/blob/master/LICENSE, então sinta-se livre para utilizar, de acordo com o que define a licença.

**Comment by EsioFreitas** [comment]
@joaaogui Certo. Obrigado.

**Comment by joaaogui** [comment]
De nada!

Quaisquer dúvidas estou a disposição!

**Comment by RochaCarla** [comment]
5 cents decontribaição: não é uma boa prática de comunidade "começar do zero" e refazer um artefato. Somente se fizer muito sentido na organização. 

Recomendo que a página seja evoluída, não refeita :)

**Comment by EsioFreitas** [comment]
> 5 cents decontribaição: não é uma boa prática de comunidade "começar do zero" e refazer um artefato. Somente se fizer muito sentido na organização.
> 
> Recomendo que a página seja evoluída, não refeita :)

Boa noite professora. @joaaogui me explicou a situação e ficou claro para mim a situação. No momento, estou na criação do protótipo para validação da evolução do que ja tem hoje [nessa issue](https://github.com/Escola-em-Casa/landing-page-escola-em-casa/issues/3).
