### ISSUE TITLE
Validação de prototipo

### ISSUE THREAD

**Issue by EsioFreitas** [Escola-em-Casa/landing-page-escola-em-casa#3]
Ola! 

Para estruturar a landing page, criei um prototipo. A ideia é que possa ser validada antes de um desenvolver e submeter um pr. Segue o link do prototipo: https://www.figma.com/file/TOUk1MfAHuez3zAjuVB3Yp/Escola-em-casa?node-id=0%3A1

Ressalto que as caixas em cinza serão textos. 

Obrigado.

**Comment by joaaogui** [comment]
@EsioFreitas Boa! Fiz alguns comentários no figma.

Valeu!

**Comment by EsioFreitas** [comment]
@joaaogui , respondi la! Vou evoluir ate final de semana e aviso aqui =D

**Comment by EsioFreitas** [comment]
@joaaogui  e @guilacerda 

Poderiam me dizer o passo-a-passo para solicitar o uso da aplicação?

**Comment by EsioFreitas** [comment]
Bom dia galera. Eu posso focar na documentação, caso isso não for importante para vcs. @joaaogui  e @guilacerda

**Comment by guilacerda** [comment]
> @joaaogui e @guilacerda
> 
> Poderiam me dizer o passo-a-passo para solicitar o uso da aplicação?

Como assim solicitar o uso da aplicação?

**Comment by EsioFreitas** [comment]
> > @joaaogui e @guilacerda
> > Poderiam me dizer o passo-a-passo para solicitar o uso da aplicação?
> 
> Como assim solicitar o uso da aplicação?

![image](https://user-images.githubusercontent.com/34384624/94608212-6f7eaf00-0273-11eb-950b-795075115590.png)

Nessa parte, a ideia seria criar um passo a passo de como funciona. 
1. cadastrar na aplicação
2. mandar x documentos
3. entrar nos sites X e Y pela aplicação

**Comment by EsioFreitas** [comment]
> > > @joaaogui e @guilacerda
> > > Poderiam me dizer o passo-a-passo para solicitar o uso da aplicação?
> > 
> > 
> > Como assim solicitar o uso da aplicação?
> 
> ![image](https://user-images.githubusercontent.com/34384624/94608212-6f7eaf00-0273-11eb-950b-795075115590.png)
> 
> Nessa parte, a ideia seria criar um passo a passo de como funciona.
> 
> 1. cadastrar na aplicação
> 2. mandar x documentos
> 3. entrar nos sites X e Y pela aplicação

No entanto, posso substituir pela FAQ @guilacerda

**Comment by joaaogui** [comment]
> @joaaogui  e @guilacerda 
> 
> Poderiam me dizer o passo-a-passo para solicitar o uso da aplicação?

Você pode usar a aplicação publicada na play store no seu celular, ou rodar a aplicação Android no Android Studio.

**Comment by joaaogui** [comment]
> > > @joaaogui e @guilacerda
> > > Poderiam me dizer o passo-a-passo para solicitar o uso da aplicação?
> > 
> > Como assim solicitar o uso da aplicação?
> 
> ![image](https://user-images.githubusercontent.com/34384624/94608212-6f7eaf00-0273-11eb-950b-795075115590.png)
> 
> Nessa parte, a ideia seria criar um passo a passo de como funciona. 
> 1. cadastrar na aplicação
> 2. mandar x documentos
> 3. entrar nos sites X e Y pela aplicação 

Acredito que acessando o app, você consiga entender melhor o fluxo da aplicação

**Comment by EsioFreitas** [comment]
Boa noite @joaaogui e @guilacerda . Terminei a versão 1.0 do protótipo. Acredito que está mais alinhado com a necessidades que vcs me apresentaram. Espero o feedback de vcs para fazer a evolução ou começar o desenvolvimento.

**Comment by EsioFreitas** [comment]
@guilacerda e @joaaogui , poderiam validar o prototipo para eu começar o esenvolvimento por favor :D

**Comment by joaaogui** [comment]
@EsioFreitas dei uma olhada, a página inicial ficou legal, na minha opinião, você já pode iniciar o desenvolvimento dela. 

Em relação a página sobre e a faq, acredito que algumas melhorias podem ser feitas. Vou comentar no próprio figma o que acho que pode melhorar, e te dou um toque por aqui :)
